"""init

Revision ID: 14f0ed9e8579
Revises: 
Create Date: 2025-11-15 01:20:11.671078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14f0ed9e8579'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('editors_choice', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Enum('interesting', 'all_apps', 'finance', 'government', 'utilities', 'transport', 'shopping', 'communication', 'entertainment', 'classifieds', 'business', 'health', 'travel', 'education', 'books', 'lifestyle', 'sport', 'news', 'parents', 'pets', 'betting', 'food', name='applicationcategoryenum'), nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('downloads', sa.Text(), nullable=True),
    sa.Column('apk_size', sa.Text(), nullable=True),
    sa.Column('screenshots', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('icon_link', sa.String(length=512), nullable=True),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('apk_link', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications', schema='public')
    op.execute('DROP TYPE applicationcategoryenum')
    # ### end Alembic commands ###
